# NOTE: To be safe, use spaces, not tabs
# Experimental Paradigm Parameters
num_stimuli: 37
overlap: 2 # do not change unless necessary - controls how many stimuli are shared with one other trial with same ref
num_stimuli_per_trial: 14
path_to_stimulus_list: '../sample-materials/image-exp-materials/sample_image_stimuli.txt'
# Modeling Parameters
sigma: 0.18
max_trials: 6000